### ISSUE TITLE
Development List of DevOps 3.1.0

### ISSUE THREAD

**Issue by shaowenchen** [kubesphere/kubesphere#3052]
target:

- fix bugs
- improve user experience

bugfix:

- [x] get error webhook link under multicluster,  https://kubesphere.com.cn/forum/d/2626-webhook-jenkins

- [x] when edit pipeline, some data get lost generated by jenkinsfile, https://github.com/kubesphere/console/issues/1270

- [x]  can not get "Docker Container Registry Credentials", https://github.com/kubesphere/console/issues/1269 -> https://github.com/kubesphere/console/pull/1290 @harrisonliu5 

- [x] chinese unit in DevOps code quality , https://github.com/kubesphere/console/issues/1278 -> https://github.com/kubesphere/console/pull/1290 @harrisonliu5 

- [x] get error when display bool parameter from Jenkinsfile in scm, https://github.com/kubesphere/kubesphere/issues/3043

feature:

- [x] approval pipeline control, https://github.com/kubesphere/kubesphere/issues/2483 https://github.com/kubesphere/kubesphere/issues/3006 

- [x] add and display the status of the pipeline on the front page, https://github.com/kubesphere/kubesphere/issues/3007 ,https://kubesphere.com.cn/forum/d/2469-devops -> https://github.com/kubesphere/kubesphere/pull/3126 @shaowenchen 

- [x] clone pipeline, https://github.com/kubesphere/kubesphere/issues/3053 https://github.com/kubesphere/kubesphere/issues/559 -> https://github.com/kubesphere/console/pull/1315/ @harrisonliu5 

- [x] batch execution pipeline, https://github.com/kubesphere/kubesphere/issues/1811 -> https://github.com/kubesphere/console/pull/1315/ @harrisonliu5 

- [x] support tag trigger pipeline, https://github.com/kubesphere/kubesphere/issues/3051 @harrisonliu5 

- [x] interactive creation pipeline, https://github.com/kubesphere/console/issues/1283 ,https://kubesphere.com.cn/forum/d/2593-rainbond/3 -> https://github.com/kubesphere/console/pull/1315/ @harrisonliu5 

- [x] **[S2I]** webhook support, https://github.com/kubesphere/s2ioperator/issues/6

improvement:

- [x] upgrade Jenkins Version, https://github.com/kubesphere/kubesphere/issues/2618 ,Jenkins distribution solution, https://github.com/kubesphere/kubesphere/issues/2182   @LinuxSuRen

- [x] human-readable error message from pipeline cron text , https://github.com/kubesphere/kubesphere/issues/2919

- [ ] **[S2I]** human readable error message, https://kubesphere.com.cn/forum/d/1882-jar-99, https://github.com/kubesphere/s2ioperator/issues/140

- [ ] **[S2I]**  quota exceeded, https://github.com/kubesphere/kubesphere/issues/2843

/area devops

**Comment by LinuxSuRen** [comment]
I'll take #2618  #2182, please assign them to me.

**Comment by LinuxSuRen** [comment]
I created one pull request #3125 for the backend and one issue https://github.com/kubesphere/console/issues/1310 for the front-end to fix  #3051

**Comment by LinuxSuRen** [comment]
I believe that this proposal can reduce some confusion about the Pipeline running status. https://github.com/kubesphere/console/issues/1326

**Comment by LinuxSuRen** [comment]
We already started to use [project](https://github.com/orgs/kubesphere/projects/3) as the plan dashboard for DevOps. I'm wondering if we can close this issue? How do you think about it @shaowenchen

**Comment by shaowenchen** [comment]
yes.

**Comment by lpfairstar** [comment]
# here is the log when i install ks-jenkins in ks3.0.0
Some plugins failed to download! Not downloaded: kubesphere-token-auth
Not downloaded: kubesphere-extension
exit beacause install plugin failed
-------------------------------------------------------------------------------
Seems I meet the same problem, does it only heppend in ks3.0.0 or there is matter with my ks-jenkins configmap?
And what should I do to fix it?

**Comment by LinuxSuRen** [comment]
hi @lpfairstar thanks for reaching out to us. We already moved DevOps into a new repo. Please see it below

https://github.com/kubesphere/ks-devops/
