### ISSUE TITLE
Development List of ServiceMesh 3.1.0

### ISSUE THREAD

**Issue by zackzhangkai** [kubesphere/kubesphere#3054]
feature：

~~De-dependence Prometheus Client For Kiali [#4](https://github.com/kubesphere/kiali/pull/4/files)~~

- [x] Use Kiali API directly  [#3](https://github.com/kubesphere/kiali/pull/3)(https://github.com/kubesphere/kubesphere/pull/3045)
- [x] Support nginx-ingress monitor https://github.com/kubesphere/ks-installer/pull/1205 

improvement: 

- [x] Upgrade Istio Version 1.6.10  [#1125](https://github.com/kubesphere/ks-installer/pull/1125)
- [x] Refactor Application. Use application of sigs.k8s.io/application directly instead of kubesphere.io/application https://github.com/wansir/kubesphere/pull/4/files

bugfix:

- [x] Fix Application Status [#3014](https://github.com/kubesphere/kubesphere/pull/3014)
- [x] FIx add component for Application https://github.com/kubesphere/console/issues/1394
- [x] Fix Application monitor https://github.com/kubesphere/console/issues/1393
- [x] Fix Grayscale Release when  service app label is not the same with the servicename  https://github.com/kubesphere/kubesphere/issues/3128
