### ISSUE TITLE
Development List of AppStore/Network/Metering in 3.1.0

### ISSUE THREAD

**Issue by zheng1** [kubesphere/kubesphere#3063]
### AppStore

- [ ] Refactoring with CRD, while fix bugs caused by legacy architecture #3036 #3001 #2995 #2981 #2954 #2951 #2783 #2713 #2700 #1903 
- [ ] Support global repo #1598

### Network

- [ ] IPPool for Calico and VMs #3057
- [ ] Support for deployment using static IPs #3058
- [ ] Support for ks-installer with porter as a system component #3059
- [ ] Support for defining porter-related configuration items in the UI #3060
- [ ] Support network visualization #3061 #583

### Metering

- [ ] Support for viewing resource consumption at the cluster,  workspace, and application template levels #3062

**Comment by leoendless** [comment]
https://github.com/kubesphere/kubesphere/issues/3075  needs to be fixed in the AppStore refactoring.
