### ISSUE TITLE
v3.1.0 roadmap for monitoring/alerting/notification/edge computing

### ISSUE THREAD

**Issue by benjaminhuo** [kubesphere/kubesphere#3071]
### Alerting
- [x] Prometheus alert/alert rule management (Alert rule CRUD, https://github.com/kubesphere/kubesphere/issues/3065)

### Notification
- [ ] Multi-tenant notification support including Email/DingTalk/Slack/Wechat/Webhook (https://github.com/kubesphere/kubesphere/issues/3066)

### Monitoring
- [x] Utilizing existing monitoring stack setup (https://github.com/kubesphere/kubesphere/issues/3068)

### Edge Computing
- [x] KubeEdge Integration (https://github.com/kubesphere/kubesphere/issues/3070)

### Monitoring
- [x] Custom monitoring enhancement (https://github.com/kubesphere/kubesphere/issues/3067)

/assign @benjaminhuo @junotx @wanjunlei @Ma-Dan @huanggze @leoendless @Carlosfengv
/kind feature-request
/area monitoring
/area alerting
/area notification
/area edge
/milestone 3.1.0

**Comment by wanjunlei** [comment]
https://github.com/kubesphere/kubesphere/issues/3196
