### ISSUE TITLE
Roadmap for e2e testing

### ISSUE THREAD

**Issue by RolandMa1986** [kubesphere/kubesphere#3333]
**What's it about?**
End-to-end (e2e) tests provide a mechanism to test end-to-end behavior of KubeSphere, and ensure end user operations match developer specifications.

E2E testing consists of several phases:
- Implementing a test suite. e2e will rely on Ginkgo for managing tests and Gomega for assertions. Tests interact with the KubeSphere cluster using a rest client.
- Bringing up a test cluster. Kind and ks-insaller can help here.
- Running an E2E test suite against that cluster.

**Feature**

- [ ] Add E2E Framework to support e2e testing
- [ ] Add a Kubernetes objects client which read/write from KubeSphere API Server
- [ ] Integrate e2e testing in CI process and collect test results

- [ ] Add e2e testing for component xxx

**Area Suggestion**
/area test
/kind feature

**Comment by zaunist** [comment]
Hi, @RolandMa1986.Is there still a plan in progress?
