### ISSUE TITLE
Checklist before releasing v3.1.0

### ISSUE THREAD

**Issue by zryfish** [kubesphere/kubesphere#3738]
The following items should be marked as resolved before releasing v3.1.0 officially.

- [x] All of [issues](https://github.com/kubesphere/kubesphere/issues?q=is%3Aopen+is%3Aissue+label%3Apriority%2Fhigh+milestone%3A3.1.0) with label `priority/high`of `milestone v3.1.0` are resolved.
- [x] The rest of `milestone 3.1.0` [issues](https://github.com/kubesphere/kubesphere/issues?q=is%3Aopen+is%3Aissue+milestone%3A3.1.0) are moved to next milestone. 
- [x] All of images required by v3.1.0 are pushed and synced to repo `kubesphere`.  #3737 
- [x] [kubesphere](https://github.com/kubesphere/kubesphere) [ks-installer](https://github.com/kubesphere/ks-installer) [console](https://github.com/kubesphere/console)  related repositories are all tagged release v3.1.0
- [x] Make sure all of CRD files are using apiVersion `apiextensions.k8s.io/v1` instead of `apiextensions.k8s.io/v1beta1`. #3708 
- [x] Sync dockerhub images to registry `aliyuncs.com/kubesphereio`. [issue](https://github.com/kubesphere/image-sync-config/issues/2)
- [x] Update base image to fix vulnerability issues. #3740

/milestone 3.1.0

**Comment by yuswift** [comment]
- [ ] release tower to v0.2.0 and update the image tag for installer
